stages:
    - pages

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone

.pages:
    image: registry.gitlab.com/hwdegroot/forsure.dev/hugo:latest
    stage: pages
    script:
        - git clean -ffdx
        - cd site
        - hugo --contentDir content/
          --config config/config.yaml
          --destination ../public/
    artifacts:
        paths:
            - public
pages:
    extends: .pages
    only:
        - tags
        - main

pages_dev:
    extends: .pages
    except:
        - tags
        - main
    when: manual


