stages:
    - build
    - pages

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_STRATEGY: clone

.deploy:
    stage: build
    image: registry.gitlab.com/hwdegroot/forsure.dev/hugo:latest

pages:
    extends: .deploy
    stage: pages
    script:
        - git clean -ffdx
        - cd static
        - hugo --contentDir content/
          --config config/config.yaml
          --destination ../public/
    artifacts:
        paths:
            - public
    only:
        - tags
        - master
