title: Rik de Groot
assetsDir: content/assets
enableRobotsTXT: true
metaDataFormat: yaml
baseURL: https://www.forsure.dev/
permalinks:
    posts: /-/:year/:month/:day/:title
    tags: /:slug
    policies: /policy/:title
languageCode: en-us
paginate: 10
themesDir: themes
theme: m10c
enableEmoji: true

enableGitInfo: true
googleAnalytics: UA-3891774-2
disqusShortname: www-forsure-dev

# Code highlight
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsStyle: monokai
pygmentsCodeFences: true

params:
    # show cookie policy
    cookiePolicy: true
    addthis: ra-5d30947f0078e16b
    author: Rik de Groot
    description: Code, cook and bake. Working @easeeonline
    avatar: images/rik-de-groot.jpg
    images:
        - images/og/cover.png
    social:
        - name: gitlab
          url: https://gitlab.com/hwdegroot
        - name: twitter
          url: https://twitter.com/hwdegroot
        - name: linkedin
          url: https://www.linkedin.com/in/rikhwdegroot/
    style:
        # green
        darkestColor: "#282e37"
        darkColor: "#3d434c"
        primaryColor: "#67eba2"
        lightColor: "#d3d3d3"
        lighestColor: "#fff"
