title: Rik de Groot
enableRobotsTXT: true
metaDataFormat: "yaml"
baseURL: "https://www.forsure.dev/"
languageCode: "en-us"
paginate: 10
themesDir: "themes"
theme: "m10c"
disablePathToLower: true
enableGitInfo: true

# Code highlight
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsStyle: monokai
pygmentsCodeFences: true

params:
    author: Rik de Groot
    description: >
        I do stuff
    avatar: https://pbs.twimg.com/profile_images/1110632196967186434/d3JdQFHO_400x400.jpg
    social:
        - name: gitlab
          url: https://gitlab.com/hwdegroot
        - name: twitter
          url: https://twitter.com/hwdegroot
        - name: linkedin
          url: https://www.linkedin.com/in/rikhwdegroot/
    style:
        # green
        darkestColor: "#282e37"
        darkColor: "#3d434c"
        primaryColor: "#67eba2"
        lightColor: "#d3d3d3"
        lighestColor: "#fff"
